package org.example.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * @Author www.hiai.top
 * @Email goodsking@163.com
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class StudentBase<M extends StudentBase<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

}
